server:
  port: 8090
spring:
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://node224119-env-teaching.j.layershift.co.uk/teaching_salary
    username: root
    password: VIAkaa12248
  jpa:
    show-sql: true
  security:
    user:
      password: admin
      name: admin
      roles: ADMIN