server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teaching_salary?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
  security:
    user:
      password: admin
      name: admin
      roles: ADMIN